version: '2'
services:

  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    restart: always
    privileged: true
    ports:
      - 3308:3306
    volumes:
      - "./data/mysql:/var/lib/mysql"          # 挂载数据目录
      - "./mysql/my.conf:/etc/mysql/conf.d"      # 挂载配置文件目录
    environment:
      MYSQL_DATABASE: buyer
      MYSQL_USER: buyer
      MYSQL_PASSWORD: pidayBuyer01!
      MYSQL_ROOT_PASSWORD: pidayBuyer01!

  redis-db:
    image: redis:5.0
    ports:
      - 6380:6379
    container_name: redis-db