version: '2'
services:
  jenkens:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
        - "50000:5000"
        - "8080:8080"
    user: root
    volumes:
    - "../data/jenkens:/var/jenkins_home"
