version: '2'
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    restart: always
    privileged: true
    ports:
      - 3308:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: micro
      MYSQL_USER: micro
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

  redis-db:
    image: redis:5.0
    ports:
      - 6380:6379
    container_name: redis-db

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    #network_mode: "host"
    restart: always
    ports:
      - 27018:27017
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data/mongo:/data/db
    command: mongod --auth
