version: '2'

services:
  kafka1:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:21811,zoo2:21812,zoo3:21813
    volumes:
    - /Users/zifang/environment/volume/kfkluster/kafka1/logs:/kafka

  kafka2:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
    - 9093:9093
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: localhost:21811,zoo2:21812,zoo3:21813
    volumes:
    - /Users/zifang/environment/volume/kfkluster/kafka2/logs:/kafka

  kafka3:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
    - 9094:9094
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: localhost:21811,zoo2:21812,zoo3:21813
    volumes:
    - /Users/zifang/environment/volume/kfkluster/kafka3/logs:/kafka
